services:
  - type: web
    name: stacxar-frontend
    env: static
    rootDir: frontend
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
